# Generated by vmake version 10.5b

# Define path to each library
LIB_WORK = work

# Define path to each design unit
VCOM = vcom
VLOG = vlog
VOPT = vopt
SCCOM = sccom

whole_library : $(LIB_WORK)/_lib.qdb

$(LIB_WORK)/_lib.qdb :

