# Generated by vmake version 10.5b

# Define path to each library
LIB_CELLSLIB = /data/public/common/software/opprog/sim_libs/CellsLib
LIB_STD = /data/public/common/software/modeltech/10.5b/modeltech/linux_x86_64/../std
LIB_IEEE = /data/public/common/software/modeltech/10.5b/modeltech/linux_x86_64/../ieee
LIB_WORK = work

# Define path to each design unit
CELLSLIB__cellslib_decl_pack = $(LIB_CELLSLIB)/cellslib_decl_pack/_primary.dat
IEEE__std_logic_1164 = $(LIB_IEEE)/_lib.qdb
STD__textio = $(LIB_STD)/_lib.qdb
IEEE__numeric_std = $(LIB_IEEE)/_lib.qdb
WORK__vga_tb_behavioural_cfg = $(LIB_WORK)/_lib.qdb
WORK__vga_tb__behavioural = $(LIB_WORK)/_lib.qdb
WORK__vga_tb__synthesised = $(LIB_WORK)/_lib.qdb
WORK__vga_tb = $(LIB_WORK)/_lib.qdb
WORK__vga_controller_behavior_cfg = $(LIB_WORK)/_lib.qdb
WORK__vga_controller__behavior = $(LIB_WORK)/_lib.qdb
WORK__vga_controller__synthesised = $(LIB_WORK)/_lib.qdb
WORK__vga_controller = $(LIB_WORK)/_lib.qdb
WORK__posnew_nextcopter_cfg = $(LIB_WORK)/_lib.qdb
WORK__posnew__synthesised = $(LIB_WORK)/_lib.qdb
WORK__posnew__nextcopter = $(LIB_WORK)/_lib.qdb
WORK__posnew = $(LIB_WORK)/_lib.qdb
WORK__pos_statemachine_cfg = $(LIB_WORK)/_lib.qdb
WORK__pos__synthesised = $(LIB_WORK)/_lib.qdb
WORK__pos__statemachine = $(LIB_WORK)/_lib.qdb
WORK__pos = $(LIB_WORK)/_lib.qdb
WORK__helicopter_toplevel_cfg = $(LIB_WORK)/_lib.qdb
WORK__helicopter__toplevel = $(LIB_WORK)/_lib.qdb
WORK__helicopter__synthesised = $(LIB_WORK)/_lib.qdb
WORK__helicopter = $(LIB_WORK)/_lib.qdb
WORK__draw_renderer_cfg = $(LIB_WORK)/_lib.qdb
WORK__draw__synthesised = $(LIB_WORK)/_lib.qdb
WORK__draw__renderer = $(LIB_WORK)/_lib.qdb
WORK__draw = $(LIB_WORK)/_lib.qdb
WORK__divider_behavior_cfg = $(LIB_WORK)/_lib.qdb
WORK__divider__behavior = $(LIB_WORK)/_lib.qdb
WORK__divider__synthesised = $(LIB_WORK)/_lib.qdb
WORK__divider = $(LIB_WORK)/_lib.qdb
VCOM = vcom
VLOG = vlog
VOPT = vopt
SCCOM = sccom

whole_library : $(LIB_WORK)/_lib.qdb

$(LIB_WORK)/_lib.qdb : VHDL/divider_SYNTH.vhd \
		$(IEEE__numeric_std) \
		$(WORK__divider) \
		$(CELLSLIB__cellslib_decl_pack) \
		$(STD__textio) \
		$(IEEE__std_logic_1164) VHDL/divider.vhd \
		$(IEEE__numeric_std) \
		$(STD__textio) \
		$(IEEE__std_logic_1164) VHDL/divider_behavior_cfg.vhd \
		$(WORK__divider__behavior) \
		$(IEEE__numeric_std) \
		$(STD__textio) \
		$(IEEE__std_logic_1164) \
		$(WORK__divider) VHDL/draw.vhd \
		$(IEEE__numeric_std) \
		$(STD__textio) \
		$(IEEE__std_logic_1164) VHDL/draw-renderer.vhd \
		$(WORK__draw) \
		$(IEEE__numeric_std) \
		$(STD__textio) \
		$(IEEE__std_logic_1164) VHDL/draw_SYNTH.vhd \
		$(IEEE__numeric_std) \
		$(WORK__draw) \
		$(CELLSLIB__cellslib_decl_pack) \
		$(STD__textio) \
		$(IEEE__std_logic_1164) VHDL/draw_renderer_cfg.vhd \
		$(WORK__draw__renderer) \
		$(IEEE__numeric_std) \
		$(STD__textio) \
		$(IEEE__std_logic_1164) \
		$(WORK__draw) VHDL/helicopter_SYNTH.vhd \
		$(IEEE__numeric_std) \
		$(WORK__helicopter) \
		$(CELLSLIB__cellslib_decl_pack) \
		$(STD__textio) \
		$(IEEE__std_logic_1164) VHDL/tld-helicopter.vhd \
		$(IEEE__numeric_std) \
		$(STD__textio) \
		$(IEEE__std_logic_1164) VHDL/helicopter_toplevel_cfg.vhd \
		$(WORK__draw) \
		$(WORK__pos) \
		$(WORK__posnew) \
		$(WORK__draw_renderer_cfg) \
		$(WORK__pos_statemachine_cfg) \
		$(WORK__posnew_nextcopter_cfg) \
		$(WORK__helicopter__toplevel) \
		$(IEEE__numeric_std) \
		$(STD__textio) \
		$(IEEE__std_logic_1164) \
		$(WORK__helicopter) VHDL/pos.vhd \
		$(IEEE__numeric_std) \
		$(STD__textio) \
		$(IEEE__std_logic_1164) VHDL/pos_SYNTH.vhd \
		$(IEEE__numeric_std) \
		$(WORK__pos) \
		$(CELLSLIB__cellslib_decl_pack) \
		$(STD__textio) \
		$(IEEE__std_logic_1164) VHDL/pos_statemachine_cfg.vhd \
		$(WORK__pos__statemachine) \
		$(IEEE__numeric_std) \
		$(STD__textio) \
		$(IEEE__std_logic_1164) \
		$(WORK__pos) VHDL/pos+.vhd \
		$(IEEE__numeric_std) \
		$(STD__textio) \
		$(IEEE__std_logic_1164) VHDL/posnew_SYNTH.vhd \
		$(IEEE__numeric_std) \
		$(WORK__posnew) \
		$(CELLSLIB__cellslib_decl_pack) \
		$(STD__textio) \
		$(IEEE__std_logic_1164) VHDL/posnew_nextcopter_cfg.vhd \
		$(WORK__posnew__nextcopter) \
		$(IEEE__numeric_std) \
		$(STD__textio) \
		$(IEEE__std_logic_1164) \
		$(WORK__posnew) VHDL/vga_controller_SYNTH.vhd \
		$(IEEE__numeric_std) \
		$(WORK__vga_controller) \
		$(CELLSLIB__cellslib_decl_pack) \
		$(STD__textio) \
		$(IEEE__std_logic_1164) VHDL/vga_controller.vhd \
		$(IEEE__numeric_std) \
		$(STD__textio) \
		$(IEEE__std_logic_1164) VHDL/vga_controller_behavior_cfg.vhd \
		$(WORK__vga_controller__behavior) \
		$(IEEE__numeric_std) \
		$(STD__textio) \
		$(IEEE__std_logic_1164) \
		$(WORK__vga_controller) VHDL/vga_tb_SYNTH.vhd \
		$(IEEE__numeric_std) \
		$(WORK__vga_tb) \
		$(CELLSLIB__cellslib_decl_pack) \
		$(STD__textio) \
		$(IEEE__std_logic_1164) VHDL/tb_divider.vhd \
		$(IEEE__numeric_std) \
		$(STD__textio) \
		$(IEEE__std_logic_1164) VHDL/vga_tb_behavioural_cfg.vhd \
		$(WORK__helicopter) \
		$(WORK__divider) \
		$(WORK__vga_controller) \
		$(WORK__helicopter_toplevel_cfg) \
		$(WORK__divider_behavior_cfg) \
		$(WORK__vga_controller_behavior_cfg) \
		$(WORK__vga_tb__behavioural) \
		$(IEEE__numeric_std) \
		$(STD__textio) \
		$(IEEE__std_logic_1164) \
		$(WORK__vga_tb)
	$(VCOM) -quiet -nologo -2008 -lower \
		 -explicit -work work VHDL/divider_SYNTH.vhd
	$(VCOM) -quiet -nologo -2008 -lower \
		 -explicit -work work VHDL/divider.vhd
	$(VCOM) -quiet -nologo -2008 -lower \
		 -explicit -work work VHDL/divider_behavior_cfg.vhd
	$(VCOM) -quiet -nologo -2008 -lower \
		 -explicit -work work VHDL/draw.vhd
	$(VCOM) -quiet -nologo -2008 -lower \
		 -explicit -work work VHDL/draw-renderer.vhd
	$(VCOM) -quiet -nologo -2008 -lower \
		 -explicit -work work VHDL/draw_SYNTH.vhd
	$(VCOM) -quiet -nologo -2008 -lower \
		 -explicit -work work VHDL/draw_renderer_cfg.vhd
	$(VCOM) -quiet -nologo -2008 -lower \
		 -explicit -work work VHDL/helicopter_SYNTH.vhd
	$(VCOM) -quiet -nologo -2008 -lower \
		 -explicit -work work VHDL/tld-helicopter.vhd
	$(VCOM) -quiet -nologo -2008 -lower \
		 -explicit -work work VHDL/helicopter_toplevel_cfg.vhd
	$(VCOM) -quiet -nologo -2008 -lower \
		 -explicit -work work VHDL/pos.vhd
	$(VCOM) -quiet -nologo -2008 -lower \
		 -explicit -work work VHDL/pos_SYNTH.vhd
	$(VCOM) -quiet -nologo -2008 -lower \
		 -explicit -work work VHDL/pos_statemachine_cfg.vhd
	$(VCOM) -quiet -nologo -2008 -lower \
		 -explicit -work work VHDL/pos+.vhd
	$(VCOM) -quiet -nologo -2008 -lower \
		 -explicit -work work VHDL/posnew_SYNTH.vhd
	$(VCOM) -quiet -nologo -2008 -lower \
		 -explicit -work work VHDL/posnew_nextcopter_cfg.vhd
	$(VCOM) -quiet -nologo -2008 -lower \
		 -explicit -work work VHDL/vga_controller_SYNTH.vhd
	$(VCOM) -quiet -nologo -2008 -lower \
		 -explicit -work work VHDL/vga_controller.vhd
	$(VCOM) -quiet -nologo -2008 -lower \
		 -explicit -work work VHDL/vga_controller_behavior_cfg.vhd
	$(VCOM) -quiet -nologo -2008 -lower \
		 -explicit -work work VHDL/vga_tb_SYNTH.vhd
	$(VCOM) -quiet -nologo -2008 -lower \
		 -explicit -work work VHDL/tb_divider.vhd
	$(VCOM) -quiet -nologo -2008 -lower \
		 -explicit -work work VHDL/vga_tb_behavioural_cfg.vhd

