-- Generated by: xvhdl 3.03 10-Aug-2015
-- Date: 11-Jan-2018 12:27:16
-- Path: /home/michaelkraaije/epo3git/epo3biem/test

LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
LIBRARY CellsLib;
USE CellsLib.CellsLib_DECL_PACK.all;

-- user directives added from .sls2vhdl


ARCHITECTURE extracted OF Helicopter IS

  SIGNAL N_1, N_2, N_3, N_4, N_5, N_6, N_7, N_8: STD_LOGIC;
  SIGNAL N_9, N_10, N_11, N_12, N_13, N_14, N_15, N_16: STD_LOGIC;
  SIGNAL N_17, N_18, N_19, N_20, N_21, N_22, N_23, N_24: STD_LOGIC;
  SIGNAL N_25, N_26, N_27, N_28, N_29, N_30, N_31, N_32: STD_LOGIC;
  SIGNAL N_33, N_34, N_35, N_36, N_37, N_38, N_39, N_40: STD_LOGIC;
  SIGNAL N_41, N_42, N_43, N_44, N_45, N_46, N_47, N_48: STD_LOGIC;
  SIGNAL N_49, N_50, N_51, N_52, N_53, N_54, N_55, N_56: STD_LOGIC;
  SIGNAL N_57, N_58, N_59, N_60, N_61, N_62, N_63, N_64: STD_LOGIC;
  SIGNAL N_65, N_66, N_67, N_68, N_69, N_70, N_71, N_72: STD_LOGIC;
  SIGNAL N_73, N_74, N_75, N_76, N_77, N_78, N_79, N_80: STD_LOGIC;
  SIGNAL N_81, N_82, N_83, N_84, N_85, N_86, N_87, N_88: STD_LOGIC;
  SIGNAL N_89, N_90, N_91, N_92, N_93, N_94, N_95, N_96: STD_LOGIC;
  SIGNAL N_97, N_98, N_99, N_100, N_101, N_102, N_103, N_104: STD_LOGIC;
  SIGNAL N_105, N_106, N_107, N_108, N_109, N_110, N_111, N_112: STD_LOGIC;
  SIGNAL N_113, N_114, N_115, N_116, N_117, N_118, N_119, N_120: STD_LOGIC;
  SIGNAL N_121, N_122, N_123, N_124, N_125, N_126, N_127, N_128: STD_LOGIC;
  SIGNAL position_new_5_port: STD_LOGIC;
  SIGNAL position_new_1_port: STD_LOGIC;
  SIGNAL position_new_4_port: STD_LOGIC;
  SIGNAL position_old_2_port: STD_LOGIC;
  SIGNAL position_new_0_port: STD_LOGIC;
  SIGNAL position_old_5_port: STD_LOGIC;
  SIGNAL position_old_0_port: STD_LOGIC;
  SIGNAL position_old_3_port: STD_LOGIC;
  SIGNAL position_new_2_port: STD_LOGIC;
  SIGNAL position_old_4_port: STD_LOGIC;
  SIGNAL position_old_1_port: STD_LOGIC;
  SIGNAL position_new_3_port: STD_LOGIC;

  SIGNAL blue_int: STD_LOGIC;

BEGIN

  blue <= blue_int;


  lbl1_position_old_reg_0_inst: dfn10 PORT MAP (N_101, clk, position_old_0_port);
  lbl1_position_old_reg_3_inst: dfn10 PORT MAP (N_30, clk, position_old_3_port);
  lbl1_position_old_reg_2_inst: dfn10 PORT MAP (N_6, clk, position_old_2_port);
  lbl1_position_old_reg_1_inst: dfn10 PORT MAP (N_110, clk, position_old_1_port);
  lbl1_position_old_reg_4_inst: dfn10 PORT MAP (N_72, clk, position_old_4_port);
  lbl1_position_old_reg_5_inst: dfn10 PORT MAP (N_83, clk, position_old_5_port);
  lbl1_state_reg_0_inst: dfr11 PORT MAP (N_25, N_87, clk, N_122);
  lbl1_state_reg_1_inst: dfr11 PORT MAP (N_127, N_87, clk, N_123);
  lbl2_U33: na310 PORT MAP (x_input(3), N_5, N_1, N_3);
  lbl2_U35: na310 PORT MAP (N_74, N_48, N_10, N_5);
  lbl2_U56: na310 PORT MAP (N_7, N_15, N_27, N_8);
  lbl2_U91: na310 PORT MAP (N_49, N_53, N_59, N_62);
  lbl2_U89: na310 PORT MAP (N_77, x_input(0), x_input(1), N_74);
  lbl1_U31: na310 PORT MAP (N_122, N_120, count, N_125);
  lbl2_U34: no310 PORT MAP (x_input(4), x_input(6), x_input(5), N_1);
  lbl2_U71: no310 PORT MAP (N_32, N_53, N_21, N_37);
  lbl2_U76: no310 PORT MAP (N_35, N_36, N_58, N_39);
  lbl2_U38: no310 PORT MAP (N_78, N_61, N_70, N_64);
  lbl2_U92: no310 PORT MAP (N_63, N_51, N_57, N_59);
  lbl2_U47: no310 PORT MAP (N_67, N_69, N_81, N_71);
  lbl2_U64: mu111 PORT MAP (N_20, N_12, position_old_1_port, N_7);
  lbl2_U36: mu111 PORT MAP (N_8, N_38, N_13, N_10);
  lbl2_U54: mu111 PORT MAP (N_47, N_28, N_31, N_67);
  lbl1_U55: mu111 PORT MAP (N_123, N_121, N_122, N_124);
  lbl0_r61_U21: na210 PORT MAP (N_102, N_104, N_113);
  lbl0_r61_U24: na210 PORT MAP (position_old_2_port, N_93, N_102);
  lbl0_r61_U15: na210 PORT MAP (N_114, N_119, N_116);
  lbl0_r61_U22: na210 PORT MAP (N_96, button, N_104);
  lbl0_r61_U10: na210 PORT MAP (N_116, position_old_4_port, N_115);
  lbl0_r61_U23: na210 PORT MAP (N_90, N_92, N_96);
  lbl0_r61_U32: na210 PORT MAP (position_old_0_port, button, N_94);
  lbl0_r61_U31: na210 PORT MAP (N_85, N_94, position_new_0_port);
  lbl0_r61_U18: na210 PORT MAP (position_old_3_port, N_113, N_114);
  lbl2_U84: na210 PORT MAP (position_old_3_port, position_old_2_port, N_50);
  lbl2_U43: na210 PORT MAP (N_4, position_old_3_port, N_73);
  lbl2_U75: na210 PORT MAP (position_old_1_port, position_old_0_port, N_46);
  lbl2_U63: na210 PORT MAP (N_55, position_old_1_port, N_19);
  lbl2_U81: na210 PORT MAP (N_55, N_44, N_33);
  lbl2_U74: na210 PORT MAP (N_44, N_46, N_47);
  lbl2_U68: na210 PORT MAP (x_input(2), N_56, N_48);
  lbl2_U37: na210 PORT MAP (N_71, N_64, N_38);
  lbl2_U70: na210 PORT MAP (N_39, N_37, N_52);
  lbl2_U69: na210 PORT MAP (N_62, N_52, N_56);
  lbl1_U36: na210 PORT MAP (N_95, N_105, N_101);
  lbl1_U33: na210 PORT MAP (N_91, N_120, N_22);
  lbl1_U37: na210 PORT MAP (position_new_0_port, N_126, N_105);
  lbl1_U38: na210 PORT MAP (position_old_0_port, N_122, N_95);
  lbl1_U44: na210 PORT MAP (position_old_2_port, N_122, N_18);
  lbl1_U42: na210 PORT MAP (N_18, N_24, N_6);
  lbl1_U43: na210 PORT MAP (position_new_2_port, N_126, N_24);
  lbl1_U32: na210 PORT MAP (N_122, N_22, N_25);
  lbl1_U47: na210 PORT MAP (position_old_3_port, N_122, N_54);
  lbl1_U50: na210 PORT MAP (position_old_4_port, N_122, N_75);
  lbl1_U48: na210 PORT MAP (N_75, N_82, N_72);
  lbl1_U51: na210 PORT MAP (N_124, N_66, N_83);
  lbl1_U46: na210 PORT MAP (position_new_3_port, N_126, N_128);
  lbl1_U49: na210 PORT MAP (position_new_4_port, N_126, N_82);
  lbl1_U52: na210 PORT MAP (position_new_5_port, N_126, N_66);
  lbl1_U45: na210 PORT MAP (N_54, N_128, N_30);
  lbl1_U40: na210 PORT MAP (position_new_1_port, N_126, N_100);
  lbl1_U39: na210 PORT MAP (N_98, N_100, N_110);
  lbl1_U41: na210 PORT MAP (position_old_1_port, N_122, N_98);
  lbl0_r61_U4: iv110 PORT MAP (position_old_2_port, N_92);
  lbl0_r61_U3: iv110 PORT MAP (N_113, N_107);
  lbl0_U7: iv110 PORT MAP (button, N_112);
  lbl0_r61_U1: iv110 PORT MAP (N_115, N_103);
  lbl0_r61_U5: iv110 PORT MAP (N_90, N_93);
  lbl0_r61_U2: iv110 PORT MAP (N_118, N_119);
  lbl0_r61_U6: iv110 PORT MAP (N_84, N_85);
  lbl2_U32: iv110 PORT MAP (N_3, blue_int);
  lbl2_U101: iv110 PORT MAP (position_old_2_port, N_41);
  lbl2_U53: iv110 PORT MAP (N_46, N_11);
  lbl2_U99: iv110 PORT MAP (N_14, N_26);
  lbl2_U96: iv110 PORT MAP (N_13, N_53);
  lbl2_U82: iv110 PORT MAP (N_23, N_44);
  lbl2_U103: iv110 PORT MAP (position_old_1_port, N_43);
  lbl2_U67: iv110 PORT MAP (y_input(1), N_31);
  lbl2_U79: iv110 PORT MAP (N_34, N_36);
  lbl2_U85: iv110 PORT MAP (position_old_4_port, N_79);
  lbl2_U90: iv110 PORT MAP (N_62, N_77);
  lbl2_U44: iv110 PORT MAP (N_76, N_78);
  lbl1_U34: iv110 PORT MAP (count, N_91);
  lbl1_U30: iv110 PORT MAP (N_125, N_127);
  lbl1_U54: iv110 PORT MAP (N_123, N_120);
  lbl1_U56: iv110 PORT MAP (position_old_5_port, N_121);
  lbl1_U35: iv110 PORT MAP (enable, N_87);
  lbl0_r61_U19: ex210 PORT MAP (N_107, N_109, position_new_3_port);
  lbl0_r61_U20: ex210 PORT MAP (N_112, position_old_3_port, N_109);
  lbl0_r61_U8: ex210 PORT MAP (N_112, position_old_5_port, N_97);
  lbl0_r61_U14: ex210 PORT MAP (position_old_4_port, button, N_89);
  lbl0_r61_U13: ex210 PORT MAP (N_116, N_89, position_new_4_port);
  lbl0_r61_U7: ex210 PORT MAP (N_99, N_97, position_new_5_port);
  lbl0_r61_U30: ex210 PORT MAP (N_112, position_old_1_port, N_108);
  lbl0_r61_U26: ex210 PORT MAP (N_92, N_112, N_88);
  lbl0_r61_U25: ex210 PORT MAP (N_93, N_88, position_new_2_port);
  lbl0_r61_U29: ex210 PORT MAP (N_85, N_108, position_new_1_port);
  lbl2_U86: ex210 PORT MAP (N_2, N_51, N_35);
  lbl2_U46: ex210 PORT MAP (N_51, N_4, N_68);
  lbl2_U94: ex210 PORT MAP (y_input(3), position_old_3_port, N_51);
  lbl2_U97: ex210 PORT MAP (position_old_0_port, y_input(0), N_13);
  lbl2_U55: ex210 PORT MAP (position_old_1_port, position_old_0_port, N_28);
  lbl2_U100: ex210 PORT MAP (y_input(2), N_41, N_14);
  lbl2_U62: ex210 PORT MAP (N_19, N_57, N_15);
  lbl2_U49: ex210 PORT MAP (y_input(2), N_17, N_69);
  lbl2_U72: ex210 PORT MAP (N_44, N_26, N_21);
  lbl2_U41: ex210 PORT MAP (N_65, N_57, N_61);
  lbl2_U58: ex210 PORT MAP (N_42, N_63, N_29);
  lbl2_U80: ex210 PORT MAP (N_33, N_57, N_34);
  lbl2_U73: ex210 PORT MAP (N_47, y_input(1), N_32);
  lbl2_U93: ex210 PORT MAP (y_input(5), position_old_5_port, N_57);
  lbl2_U60: ex210 PORT MAP (N_45, N_51, N_40);
  lbl2_U77: ex210 PORT MAP (N_60, N_63, N_58);
  lbl2_U95: ex210 PORT MAP (y_input(4), position_old_4_port, N_63);
  lbl2_U48: ex210 PORT MAP (x_input(2), x_input(0), N_81);
  lbl2_U40: ex210 PORT MAP (y_input(4), N_79, N_80);
  lbl2_U39: ex210 PORT MAP (N_73, N_80, N_70);
  lbl0_r61_U11: no210 PORT MAP (N_112, N_117, N_106);
  lbl0_r61_U12: no210 PORT MAP (position_old_4_port, N_116, N_117);
  lbl0_r61_U33: no210 PORT MAP (button, position_old_0_port, N_84);
  lbl0_r61_U9: no210 PORT MAP (N_106, N_103, N_99);
  lbl0_r61_U27: no210 PORT MAP (N_86, position_old_1_port, N_90);
  lbl0_r61_U28: no210 PORT MAP (button, N_84, N_86);
  lbl0_r61_U16: no210 PORT MAP (N_111, N_112, N_118);
  lbl0_r61_U17: no210 PORT MAP (N_113, position_old_3_port, N_111);
  lbl2_U51: no210 PORT MAP (N_46, N_41, N_4);
  lbl2_U87: no210 PORT MAP (N_23, N_41, N_2);
  lbl2_U78: no210 PORT MAP (N_23, N_50, N_60);
  lbl2_U50: no210 PORT MAP (N_9, N_4, N_17);
  lbl2_U88: no210 PORT MAP (position_old_0_port, position_old_1_port, N_23);
  lbl2_U52: no210 PORT MAP (position_old_2_port, N_11, N_9);
  lbl2_U65: no210 PORT MAP (y_input(1), N_14, N_12);
  lbl2_U98: no210 PORT MAP (N_16, N_26, N_49);
  lbl2_U66: no210 PORT MAP (N_26, N_31, N_20);
  lbl2_U102: no210 PORT MAP (y_input(1), N_43, N_16);
  lbl2_U57: no210 PORT MAP (N_40, N_29, N_27);
  lbl2_U61: no210 PORT MAP (N_41, N_43, N_45);
  lbl2_U59: no210 PORT MAP (N_43, N_50, N_42);
  lbl2_U83: no210 PORT MAP (N_79, N_50, N_55);
  lbl2_U42: no210 PORT MAP (N_79, N_73, N_65);
  lbl2_U45: no210 PORT MAP (N_68, x_input(1), N_76);
  lbl1_U53: no210 PORT MAP (N_120, N_122, N_126);

END extracted;



